# Generated by Django 4.0.6 on 2022-08-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xtracto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='document',
            field=models.FileField(upload_to='media/store/'),
        ),
    ]
